# Generated by Django 2.1 on 2019-05-11 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='developer',
            name='blogsite',
            field=models.URLField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='developer',
            name='seniority',
            field=models.CharField(default='junior', max_length=20),
        ),
    ]
